# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [10]:
import numpy as np
import random2

In [20]:
arr = np.random.randint(1,21,size=(5,5))
arr

array([[12, 11,  9, 17,  6],
       [ 5,  2,  3,  8, 14],
       [13,  5, 13, 10,  7],
       [ 2, 20, 18,  6,  8],
       [ 2, 16, 19, 14, 15]])

In [21]:
arr[2:3]=1

In [22]:
arr

array([[12, 11,  9, 17,  6],
       [ 5,  2,  3,  8, 14],
       [ 1,  1,  1,  1,  1],
       [ 2, 20, 18,  6,  8],
       [ 2, 16, 19, 14, 15]])

In [23]:
arr2 = np.random.randint(1,17,size=(4,4))

In [24]:
arr2

array([[ 5, 15,  3, 14],
       [ 8,  4,  6,  6],
       [ 4, 10,  6,  7],
       [ 5, 16,  3, 14]])

In [25]:
for i in range(4):
    arr2[i][i] = 0

In [26]:
arr2

array([[ 0, 15,  3, 14],
       [ 8,  0,  6,  6],
       [ 4, 10,  0,  7],
       [ 5, 16,  3,  0]])

In [28]:
arr3 = np.random.randint(1,37,size=(6,6))
arr3

array([[30, 19, 20, 20, 20, 12],
       [31, 13,  4, 13, 14, 10],
       [33,  9, 25, 13, 10, 13],
       [15, 18, 23, 24, 10,  4],
       [ 9, 25,  9,  9, 19,  9],
       [18, 12, 34, 28, 34, 26]])

In [29]:
arr = arr3[2:4]
arr

array([[33,  9, 25, 13, 10, 13],
       [15, 18, 23, 24, 10,  4]])

In [38]:
arr = arr3[0:6,3:5]

In [39]:
arr

array([[20, 20],
       [13, 14],
       [13, 10],
       [24, 10],
       [ 9, 19],
       [28, 34]])

In [42]:
arr1 = np.random.randint(1,21,size=(5,5))
arr2 = np.random.randint(21,41,size=(5,5))
print(arr1) 
arr2

[[ 3 12 15  2 16]
 [ 8 16  3 20 12]
 [ 7 19 15 16 19]
 [14 16 15  9 15]
 [ 9  3 19 16 14]]


array([[30, 32, 38, 40, 33],
       [39, 40, 21, 28, 38],
       [35, 40, 39, 22, 32],
       [26, 32, 37, 34, 25],
       [33, 22, 24, 32, 32]])

In [43]:
add = arr1 + arr2
add

array([[33, 44, 53, 42, 49],
       [47, 56, 24, 48, 50],
       [42, 59, 54, 38, 51],
       [40, 48, 52, 43, 40],
       [42, 25, 43, 48, 46]])

In [44]:
sub = arr2 - arr1
sub

array([[27, 20, 23, 38, 17],
       [31, 24, 18,  8, 26],
       [28, 21, 24,  6, 13],
       [12, 16, 22, 25, 10],
       [24, 19,  5, 16, 18]])

In [46]:
mul = arr1 * arr2
mul

array([[ 90, 384, 570,  80, 528],
       [312, 640,  63, 560, 456],
       [245, 760, 585, 352, 608],
       [364, 512, 555, 306, 375],
       [297,  66, 456, 512, 448]])

In [48]:
div = arr2 // arr1
div

array([[10,  2,  2, 20,  2],
       [ 4,  2,  7,  1,  3],
       [ 5,  2,  2,  1,  1],
       [ 1,  2,  2,  3,  1],
       [ 3,  7,  1,  2,  2]])

In [50]:
arr = np.random.randint(1,17,size=(4,4))
arr

array([[10, 10, 12,  1],
       [13, 13, 12, 14],
       [ 1,  4,  1,  4],
       [ 1, 12,  7, 14]])

In [52]:
rowsum = np.sum(arr,axis=1)
rowsum

array([33, 52, 10, 34])

In [53]:
colsum = np.sum(arr,axis=0)
colsum

array([25, 39, 32, 33])

In [56]:
# ### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [60]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
print ("mean = ",np.mean(arr))
print ("median = ",np.median(arr))
print ("std = ",np.std(arr))
print ("var = ",np.var(arr))


mean =  13.0
median =  13.0
std =  7.211102550927978
var =  52.0


In [ ]:
# Compute mean and standard deviation
mean = arr.mean()
std = arr.std()

# Normalize
normalized_arr = (arr - mean) / std
print("\nNormalized array:\n", normalized_arr)



Normalized array:
 [[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [-1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]]


In [67]:
a =normalized_arr.mean()
a


np.float64(-0.48)

In [68]:
col_vec = np.array([[1], [2], [3]])   # explicitly column-shaped
print("\nColumn vector:\n", col_vec)
print("Shape:", col_vec.shape)


Column vector:
 [[1]
 [2]
 [3]]
Shape: (3, 1)


In [ ]:

arr = np.random.randint(1, 11, size=(3, 3))
print("Original 3x3 array:\n", arr)


Original 3x3 array:
 [[6 9 3]
 [7 8 6]
 [8 9 5]]


In [70]:
result = arr + col_vec
print("\nResult after broadcasting:\n", result)




Result after broadcasting:
 [[ 7 10  4]
 [ 9 10  8]
 [11 12  8]]
