In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr2 = np.arange(1,10,3)

In [9]:
arr2

array([1, 4, 7])

In [10]:
arr3 = np.ones((2,3))

In [13]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

ValueError: cannot reshape array of size 3 into shape (3,2)